texto = input()

texto = texto.replace("1",".um.")
texto = texto.replace("2",".dois.")
texto = texto.replace("3",".tres.")
texto = texto.replace("4",".quatro.")
texto = texto.replace("5",".cinco.")
texto = texto.replace("6",".seis.")
texto = texto.replace("7",".sete.")
texto = texto.replace("8",".oito.")
texto = texto.replace("9",".novo.")
texto = texto.replace("0",".zero.")
texto = texto.replace("..",".")
print(texto)